### ISSUE TITLE
Podcaster Wallet issues 

### ISSUE THREAD

**Issue by WhichCarolina** [satoshisstream/satoshis.stream#1]
I am having an issue getting my satoshisStream bot set up 

I am entering my podcast rss feed from Podcast index but its telling me that "could not find podcast in podcastindex.org database 

But my podcast is on Podcast index 

Any ideas or assistance? thanks!

**Comment by satoshisstream** [comment]
What is the feed URL?

**Comment by WhichCarolina** [comment]
https://whichcarolina.libsyn.com/rss

This is my RSS Feed URL for the podcast.... it should already be hosted on
Podcastindex

**Comment by satoshisstream** [comment]
The feed URL you posted indeed is in podcastindex. 

It seems you have value sending (already) enabled, to 03b1c6cb913cd2f9a4ff449d8f6e40c51e63e6c29740e1b1985d809bce876f124d . Do you know how this was enabled?

If I enter details I get:
> This feed is already claimed. Please log in to your account to manage it.

Details:

`{"status":"true","query":{"url":"https:\/\/whichcarolina.libsyn.com\/rss"},"feed":{"id":249353,"title":"Which Carolina","url":"https:\/\/whichcarolina.libsyn.com\/rss","originalUrl":"https:\/\/whichcarolina.podomatic.com\/rss2.xml","link":"https:\/\/whichcarolina.podomatic.com","description":"Which Carolina is a sports podcast focused primarily on the NBA, The Charlotte Hornets, College basketball, and the NBA Draft \r\n\r\nWhich Carolina features 3 main hosts and expert guests and friends of the show!","author":"Lee Branscome","ownerName":"Lee Branscome","image":"https:\/\/ssl-static.libsyn.com\/p\/assets\/0\/e\/3\/a\/0e3ab098351a4b73\/3000x3000-2917x29172345_14205229.jpg","artwork":"https:\/\/ssl-static.libsyn.com\/p\/assets\/0\/e\/3\/a\/0e3ab098351a4b73\/3000x3000-2917x29172345_14205229.jpg","lastUpdateTime":1616832028,"lastCrawlTime":1616832067,"lastParseTime":1616832073,"lastGoodHttpStatusTime":1616832067,"lastHttpStatus":200,"contentType":"application\/rss+xml; charset=utf-8","itunesId":1471565505,"generator":"Libsyn WebEngine 2.0","language":"en-us","type":0,"dead":0,"chash":"742c3cb7f065a5f51e2f52d0a3ba98da","episodeCount":93,"crawlErrors":0,"parseErrors":0,"categories":{"86":"Sports"},"locked":0,"imageUrlHash":4071530977,"value":{"model":{"type":"lightning","method":"keysend","suggested":"0.00000005000"},"destinations":[{"name":"Podcaster","address":"03b1c6cb913cd2f9a4ff449d8f6e40c51e63e6c29740e1b1985d809bce876f124d","type":"node","split":100},{"name":"Podcastindex.org","address":"03ae9f91a0cb8ff43840e3c322c4c61f019d8c1c3cea15a25cfc425ac605e61a4a","type":"node","fee":true,"split":1}]}},"description":"Found matching feed."}`

**Comment by WhichCarolina** [comment]
I believe I enabled it via Podcastwallet?

I also have my RSS feed populated in SphnixChat

But, I am still having trouble getting my bot set up in telegram to work,
because its saying that my rss feed can not be identified in podcastindex

Thanks so much for all the help, let me know if there is anything further i
should do?

**Comment by satoshisstream** [comment]
I see a node ID in your feed but it is not SatoshisStream's node ID...

03b1c6cb913cd2f9a4ff449d8f6e40c51e63e6c29740e1b1985d809bce876f124d is the key that was added.

I expect 03c457fafbc8b91b462ef0b8f61d4fd96577a4b58c18b50e59621fd0f41a8ae1a4.

So the node is not correct I think.

Can you join https://t.me/joinchat/fXmTB7f1e-EyMmRk ?

**Comment by WhichCarolina** [comment]
Hi, thank you

I did join that telegram group

My node might be the node im using from SPHNIX CHAT?

Its not my node, its sphinx nod and I am using it

Thanks for any more help you can provide

**Comment by satoshisstream** [comment]
Let's solve in the group.

I see you set the correct node. Now only thing left is to claim the podcast in the bot. You are very close!
