### ISSUE TITLE
Unable to claim podcast

### ISSUE THREAD

**Issue by currentc57** [satoshisstream/satoshis.stream#2]
I'm unable to claim any of my podcasts.  
I've followed the instructions up to step 3 in claiming your podcast, it's been several hours and it won't claim my podcasts.  As far as I can tell, I've followed and completed all of the steps up to that point correctly.  
my feeds are:
https://feeds.fireside.fm/thelocksportscast/rss
https://feeds.fireside.fm/truecrimeandconsequences/rss
https://anchor.fm/s/4cde0764/podcast/rss

**Comment by satoshisstream** [comment]
Hey, it seems your feed only show part of your shownotes:

`            "description": "<p>Full show notes, including links, can be found at<\/p>\n<p>http:\/\/www.thelocksportscast.com&nbsp;<\/p>\n<p>In this week&rsquo;s episode:<\/p>\n<p>-LPL quoted in argument against a gun storage bill<\/p>\n<p>-Copying a Key Using a Plastic Bottle<\/p>\n<p>-A 6' 2\" tall padlock<\/p>\n<p>-First pick of the Medeco M4<\/p>\n<p>-Mow&rsquo;s plongus video<\/p>\n<p>-Deviant Ollam on The Hacker Mind podcast<\/p>\n<p>-What is a Lock Stick?<\/p>\n<p>-Roon on fire, again<\/p>\n<p>-Two new Lock Noob products<\/p>\n<p>-The 1831 City Bank...",`

The code must be in the actual description in the feed... Could it be it dropped off?

**Comment by currentc57** [comment]
I wonder why you're not seeing the full description.  When I click on the feed link above, I get a full description, including the CLAIM code at the bottom.  Maybe I should move the CLAIM to the top temporarily? 

`<description><p>Full show notes, including links, can be found at</p> <p><a href="http://www.thelocksportscast.com">http://www.thelocksportscast.com</a>&nbsp;</p> <p><strong>In this week&rsquo;s episode:</strong></p> <p>-LPL quoted in argument against a gun storage bill</p> <p>-Copying a Key Using a Plastic Bottle</p> <p>-A 6' 2" tall padlock</p> <p>-First pick of the Medeco M4</p> <p>-Mow&rsquo;s plongus video</p> <p>-Deviant Ollam on The Hacker Mind podcast</p> <p>-What is a Lock Stick?</p> <p>-Roon on fire, again</p> <p>-Two new Lock Noob products</p> <p>-The 1831 City Bank of New York Robbery</p> <p>-Thief Uses Locksmith to Steal Car in Oakland&nbsp;</p> <p>-Sales</p> <p>-Giveaways</p> <p><strong>Contact Information:</strong></p> <p>Email: <a href="mailto:podcast@thelocksportscast.com">podcast@thelocksportscast.com</a></p> <p>Twitter <a href="https://twitter.com/charlescurrent">https://twitter.com/charlescurrent</a>&nbsp;</p> <p>Reddit: currentc57 on r/locksport</p> <p>Discord: Lockpickers United as Current, Extraordinary League of Pickers as Current, <a href="https://discord.gg/ssRUfWR">CBC</a> as Current</p> <p>Join the Discord at <a href="http://discord.thelocksportscast.com">http://discord.thelocksportscast.com</a></p> <p>Donate:</p> <p> <a href="http://paypal.thelocksportscast.com">http://paypal.thelocksportscast.com</a></p> <p> <a href="https://patreon.com/thelocksportscast">https://patreon.com/thelocksportscast</a></p> <p> <a href="https://teespring.com/stores/the-lock-sportscast">The Lock Sportscast merch</a>&nbsp;</p> <p> <a href="https://teespring.com/stores/charles-builds-crap">CBC merch</a>&nbsp;</p> <p><strong>Executive Producer:</strong></p> <p>-Bob B</p> <p><strong>Founding Executive Producers</strong>:</p> <p>-<a href="https://www.youtube.com/channel/UCamhJgWu2mWEZxm6cB_W48A">m3ddl3r</a></p> <p>-<a href="https://www.youtube.com/channel/UCmIqJOrfQr8NTEDrOU2lF3Q">Panda-Frog</a></p> <p>-<a href="https://www.youtube.com/user/norlin76">Michael Gilchrist</a></p> <p>-<a href="https://www.youtube.com/c/Starrylock_Locksport">Starrylock</a></p> <p>-<a href="https://www.youtube.com/channel/UCRGmm9FQqF6HMu9-wq9ODSQ">WilliamsBrain</a>&nbsp;</p> <p>-<a href="https://www.youtube.com/channel/UC0X0TTCPK5kBRY3yDu40EKg">Dave 2BDCy4D</a> </p> <p>-<a href="https://www.youtube.com/channel/UCOsQqptcx3kTblkxUjHAJmg">Liibans Locksports Journey&nbsp;</a></p> <p>-<a href="https://uncensoredtactical.com/">Pat from Uncensored Tactical</a>&nbsp;</p> <p>-BillN</p> <p>-<a href="https://www.youtube.com/channel/UCxPkKy6EhE16IHrKsCk9FeQ">PHpicker</a>&nbsp;</p> <p>-<a href="https://youtube.com/channel/UCMjGnC1m9XlN_X8OHVwxphQ">threeraccoonsinacoat</a>&nbsp;</p> <p><strong>Chief Content Producer:</strong></p> <p>-<a href="https://www.youtube.com/channel/UCwPTxD1-2PPgmi6ATOJKlUw">Chirael</a></p> <p><strong>Content Producers:</strong></p> <p>-<a href="https://www.youtube.com/channel/UCGUL42kqugDD883JkBYKHHg">Theboneinthebox</a></p> <p>-<a href="https://youtube.com/channel/UCMjGnC1m9XlN_X8OHVwxphQ">threeraccoonsinacoat</a></p> <p>-<a href="https://www.youtube.com/channel/UCz1ZFs1rAG2Rsl3CucijDMw">Joshua Gonzalez</a>&nbsp;</p> <p>-<a href="https://www.youtube.com/channel/UC1ZPB5vWuL8d6C81ba75yZA">HVLogic</a>&nbsp;</p> <p>-<a href="https://www.youtube.com/channel/UC0uDsWpm4sISpzKlB0XVFDw">RoonPicker</a>&nbsp;</p> <p>-<a href="https://www.youtube.com/channel/UCT3o0I9V2RtF67A42wN3Cgg">Michael Gilchrist</a>&nbsp;</p> <p>-<a href="https://www.zieh-fix.com/">WENDT</a>&nbsp;</p> <p>-<a href="https://www.youtube.com/channel/UCmIqJOrfQr8NTEDrOU2lF3Q">Panda-Frog</a></p> <p>-<a href="https://www.youtube.com/channel/UCxPkKy6EhE16IHrKsCk9FeQ">PHpicker</a>&nbsp;</p> <p>-<a href="https://www.youtube.com/c/Starrylock_Locksport">Starrylock</a></p> <p>-<a href="https://www.youtube.com/channel/UCaJka3C3AnZYkUbNGbeAx3Q">Pocket Women</a></p> <p><strong>Special Thanks:</strong></p> <p><strong>Announcements:</strong></p> <p><a href="https://www.thelocksportscast.com/">https://www.thelocksportscast.com/</a>&nbsp;</p> <p><strong>Corrections and Additions</strong>:</p> <p><strong>Recent stories related to locksport:</strong></p> <p><a href="https://pagetwo.completecolorado.com/2021/03/16/armstrong-gun-storage-bill-misses-its-target/">Armstrong: Gun storage bill misses its target &ndash; Complete Colorado &ndash; Page Two</a>&nbsp;</p> <p><a href="https://www.youtube.com/watch?v=Nzb1L-DSzaA">Copying a Key Using a Plastic Bottle (with LockPickingLawyer)</a></p> <p><a href="https://www.dnaindia.com/india/video-elderly-couple-makes-a-unique-lock-weighing-over-300-kilograms-2881733">Elderly couple makes a unique lock weighing over 300 kilograms</a></p> <p><strong>Community News:</strong></p> <p><a href="https://youtu.be/iPRA_5GO35Y">Temporary Video - Medeco M4 Pick and Gut</a></p> <p><a href="https://www.youtube.com/watch?v=NTD5ARTNQMU">LPU Teardown ASSA Twin Exclusive 5700</a></p> <p><a href="https://thehackermind.com/ep-16-the-gentle-art-of-lockpicking">The Hacker Mind - EP16 The Gentle Art of Lockpicking</a></p> <p><a href="https://www.youtube.com/watch?v=ozDXPKah6S4">Lock Stick?</a></p> <p><a href="https://youtu.be/_zJ0ZDkAEjg">Worlds First! Izis Picked on 900,000+ Scoville Hot Sauce!</a></p> <p><strong>SpeedLocks Records:</strong></p> <p><strong>New Products:</strong></p> <p><a href="https://www.youtube.com/watch?v=Z9t-4p8lnU4">Multipick Elite 39 &lsquo;Lock Noob&rsquo; Essential Selection Kit</a></p> <p><a href="https://shop.multipick.com/en/lock-picking-lock-manipulation/multipick-elite-lockpicking-world/multipick-elite-lock-pick-sets/multipick-elite-39-lock-noobs-essential-selection-kit">Multipick ELITE 39 &bdquo;Lock Noob's&ldquo; Essential Selection Kit-MP3PNS16</a></p> <p><a href="https://www.youtube.com/watch?v=a0wXz6WwNE0">(1871) Review: Multipick's Lock Noob Pick Kit</a></p> <p><a href="https://www.sparrowslockpicks.com/product_p/warycard.htm">Be WARY!</a></p> <p><a href="https://www.hooligankeys.com/shop/FoxHole-Security-Impressioning-Handle-Metric-p310180379">FoxHole-Security-Impressioning-Handle-Metric</a></p> <p><a href="https://youtu.be/-sfFa-YQz6g">(122) Reviewing the SWICK</a>&nbsp;</p> <p><a href="https://youtu.be/NDHq6RP3WwE">SWICK How To</a></p> <p><a href="https://www.kickstarter.com/projects/989801874/swick-the-swiss-army-knife-of-picks/posts">SWICK - The World's Most Versatile Pick by David Storm &mdash; Kickstarter</a>&nbsp;</p> <p><strong>Resources:</strong></p> <p><strong>Criminals:</strong></p> <p><a href="https://youtu.be/hqFMLDfDpfs">The 1831 City Bank of New York Robbery</a></p> <p><a href="https://www.nbcbayarea.com/news/local/east-bay/thieve-uses-locksmith-to-steal-car-in-oakland/2491764/">Thief Uses Locksmith to Steal Car in Oakland</a>&nbsp;</p> <p><strong>Sales:</strong></p> <p><strong>-</strong><a href="https://hooligankeys.com/">https://hooligankeys.com/</a> <strong>NEWSTUFF21</strong> for <strong>15% off</strong></p> <p>-<a href="https://www.3dlocksport.com">https://www.3dlocksport.com</a> <strong>10% off</strong> with code <strong>PACLOCK10</strong></p> <p>-<a href="https://makolocks.com/">https://makolocks.com/</a> <strong>15% off </strong>with code <strong>BUYMAKO</strong> Unknown exp</p> <p>-MAKO Locks <a href="https://makolocks.com/collections/black-friday-specials">Black Friday Specials</a> Also the code above works on these deals!</p> <p>-<a href="https://uklockpickers.co.uk/">https://uklockpickers.co.uk/</a> <strong>10% off</strong> with code <strong>GIFT</strong></p> <p><strong>Giveaways and Contests:</strong></p> <p>-Bosnian Bill</p> <p> <a href="https://www.youtube.com/watch?v=a0wXz6WwNE0">(1871) Review: Multipick's Lock Noob Pick Kit</a>&nbsp;</p> <p>-Michael Gilchrist</p> <p> <a href="https://youtu.be/dTEQGvXpFe0">[L108] #Norlin400 Giveaway! Also American 1100 and Brady 71/40 picked</a>&nbsp;</p> <p>-Tallanpick</p> <p> <a href="https://www.youtube.com/watch?v=RLu93x2gK0U">50.000 SUSCRIPTORES GIVEAWAY! eng sub</a>&nbsp;</p> <p>-RoonPicker</p> <p> <a href="https://www.youtube.com/watch?v=LhKPrAXg9ww&amp;t=400s">Channel Update and Giveaway Announcement!</a>&nbsp;</p> <p>-PHpicker&nbsp;</p> <p> <a href="https://youtu.be/CmwOgKBHQ8E">(26) 100 sub giveaway #PH100</a>&nbsp;</p> <p> <a href="https://youtu.be/1bMKfAiisGw">(24) Announcing my New Picker giveaway #PHNewPicker</a></p> <p>-Panda-Frog</p> <p><a href="https://youtu.be/EDnq0jz0_1Y">(ENG-152) Lockpicking - Giveaway result 21Feb and the new Giveaway #PandaFrog21Mar</a></p> <p>-Starrylock - <a href="https://www.youtube.com/user/DrSteveSick/">#shoutoutMonday</a></p> <p> -<a href="https://www.youtube.com/user/DrSteveSick/">Starrylock</a>&nbsp;</p> <p> -<a href="https://www.youtube.com/channel/UCaJka3C3AnZYkUbNGbeAx3Q">Pocket Women</a></p> <p>-CLK Supplies</p> <p> <a href="https://www.youtube.com/watch?v=RowW12owkTk">Introducing #Lockboss Free Giveaway! Do you work with Locks &amp; Keys or do Locksmithing?</a>&nbsp;</p> <p>-Charles Builds Crap on YouTube - To encourage you to send me information for this show, I&rsquo;m changing the rules for my PAM Giveaway (see rules below) or <a href="https://www.thelocksportscast.com/p/paclock-a-month-giveaway/">https://www.thelocksportscast.com/p/paclock-a-month-giveaway/</a> <a href="https://www.youtube.com/user/MrCharlesCurrent">https://www.youtube.com/user/MrCharlesCurrent</a></p> <p>&ldquo;PacLock a Month&rdquo; Rules:</p> <p>I&rsquo;m giving away one of my custom PacLock 100A padlocks every month.&nbsp;</p> <p>To be entered, you must:</p> <p> 1.Provide me with locksport or locksport community news that I can use on my weekly podcast.</p> <p> -Submit your news via one of the following:</p> <p> +Email: podcast@thelocksportscast.com</p> <p> +Reddit: currentc57 on r/locksport</p> <p> +Discord: You can find me on the following servers as &ldquo;Current&rdquo;</p> <p> ~Lockpickers United&nbsp;</p> <p> ~Extraordinary League of Pickers&nbsp;</p> <p> ~CBC</p> <p> -You will receive 1 entry for each news item I use in the podcast that month.</p> <p> 2.Share the podcast on social media</p> <p> -Make sure I know about it by tagging me and/or emailing me a screenshot or other proof.</p> <p>The winner will be drawn and announced the following month. The winner will have 1 week to contact me via email to claim the prize.</p> <p>I will pay for shipping within the U.S. If you live outside the U.S., you can still enter, but must pay to ship if you win.</p> <p>I reserve the right to change these rules as I need to during the course of the year.</p> <p>I reserve the right to disqualify anyone for any reason. My decisions are final.</p> <p>This giveaway is a thank you to the subscribers that watch my videos, listen to my podcast, and help me produce it. </p> <p>YouTube, Podbean, Fireside.fm, PacLock and other entities are in no way partners to this contest, and all applicants agree to release them from any and all liability related to this contest.</p> <p>Personal data collected as a part of this contest will be used only for the purposes of this contest and will not be released to third parties.</p> <p>Any entries that violate YouTube's community guidelines will be disqualified: <a href="http://www.youtube.com/t/community_guidelines">http://www.youtube.com/t/community_guidelines</a>&nbsp;</p> CLAIM=77b6bafd033a5aec11fb5f842c47b008d379d64e=CLAIM </description>`

**Comment by currentc57** [comment]
I moved it up near the top on that feed and it worked.

**Comment by currentc57** [comment]
It would appear that even in the short description on my Anchor feed, the CLAIM needs to be at the top in order to work.  They are all successfully claimed now.  Thanks.

**Comment by satoshisstream** [comment]
Great to hear & thanks for letting me know!
