### ISSUE TITLE
Process base64-encoded podcast custom record data

### ISSUE THREAD

**Issue by coldacid** [satoshisstream/satoshis.stream#22]
Some software may doubly-encode custom record 7629169, and in fact this happened at least with a boost I sent to a podcast using satoshis.stream a few days ago. If the custom record appears to be still encoded after decoding it, try decoding it again to get the JSON payload.

**Comment by satoshisstream** [comment]
Is it then double JSON encoded? Or binary?

**Comment by satoshisstream** [comment]
Hmm base64?? So it's JSON wrapped in Base64? Any utf-encoding going on somewhere? Can you give the "chain" it is (wrongly) wrapped in?

**Comment by coldacid** [comment]
Yeah it's base64-encoded JSON rather than plain JSON.

**Comment by satoshisstream** [comment]
Is this still happening?

**Comment by coldacid** [comment]
It isn't doing it with BoostCLI, but I wouldn't be surprised if other clients might do this now or in the future.

**Comment by satoshisstream** [comment]
Had not seen it before, probably just a one time mistake. There is no base64 mention in the spec (bolt10) so I guess we will leave it at this ;). Thanks for reporting though.
