### ISSUE TITLE
Multiple payments in one record

### ISSUE THREAD

**Issue by dellagustin** [satoshisstream/satoshis.stream#6]
Hello, for the use case where a user listens to podcasts while offline, or even a player decided to aggregate payments for a longer time (i.e. a week), then it would not be possible to send the record as it currently is.
An array would be more suitable, so I suggest to optionally accept an array of objects with the currently defined format.

Also I suggest adding adding the information on the duration in seconds for which the amount was accounted.

**Comment by satoshisstream** [comment]
Good point. 

We might consider what fields would repeat... 

We could define `actions` as a list of actions:

'actions':[
 { 'action': 'stream', ts:1336 },
 { 'action': 'stream', ts:1337 },
 { 'action': 'stream', ts:1338 }
]

Or just repeat the whole record (easier to implement)...

**Comment by satoshisstream** [comment]
Please see proposed: https://github.com/satoshisstream/satoshis.stream/blob/satoshisstream-batchingpayments/TLV_registry.md#field-7629169

Allowing for a list of the same field and adding value_msat.

**Comment by dellagustin** [comment]
having just an array of the full records looks good to me.

**Comment by satoshisstream** [comment]
Cool let's merge that!
